# Site settings
title: 不要叔叔的技术宅基地
email: kerwinzheng@126.com
permalink: /:year/:month/:day/:title
exclude: [Gemfile,Gmefile.lock]
description: > # this means to ignore newlines until "baseurl:"
  企鹅550970256
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://buyaoshushu.github.io" # the base hostname & protocol for your site
github_username: buyaoshushu 
# Build settings
markdown: kramdown
production_url: "http://buyaoshushu.github.io"